// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeedbackMiner.Migrations
{
    [DbContext(typeof(FeedbackDbContext))]
    partial class FeedbackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActionRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AffectedAreasJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BenefitSegmentsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedEffort")
                        .HasColumnType("int");

                    b.Property<double>("ImpactScore")
                        .HasColumnType("float");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("UsefulnessRating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.ToTable("ActionRecommendations");
                });

            modelBuilder.Entity("ActionRecommendationEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionRecommendationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedTimelineDays")
                        .HasColumnType("int");

                    b.Property<Guid>("EvaluationRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExpectedImpact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FeasibilityScore")
                        .HasColumnType("float");

                    b.Property<bool>("MetUsefulnessThreshold")
                        .HasColumnType("bit");

                    b.Property<double>("UsefulnessScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ActionRecommendationId");

                    b.HasIndex("EvaluationRunId");

                    b.ToTable("ActionRecommendationEvaluations");
                });

            modelBuilder.Entity("EvaluationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageRecommendationUsefulnessScore")
                        .HasColumnType("float");

                    b.Property<double>("AverageSilhouetteScore")
                        .HasColumnType("float");

                    b.Property<double>("AverageThemeRelevanceScore")
                        .HasColumnType("float");

                    b.Property<double>("ClusteringPrecision")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DuplicateDetectionRate")
                        .HasColumnType("float");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OverallQualityScore")
                        .HasColumnType("float");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("RecommendationUsefulnessMetPercentage")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ThemeRelevanceMetPercentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingRunId");

                    b.ToTable("EvaluationRuns");
                });

            modelBuilder.Entity("FeedbackItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmbeddingJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentimentLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SentimentScore")
                        .HasColumnType("float");

                    b.Property<double?>("SimilarityScore")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ThemeClusterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ThemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrgencyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("UrgencyScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ThemeClusterId");

                    b.HasIndex("ThemeId");

                    b.ToTable("FeedbackItems");
                });

            modelBuilder.Entity("ProcessingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageActionUsefulness")
                        .HasColumnType("float");

                    b.Property<double>("AverageClusterQuality")
                        .HasColumnType("float");

                    b.Property<double>("AverageThemeRelevance")
                        .HasColumnType("float");

                    b.Property<int>("ClusterCount")
                        .HasColumnType("int");

                    b.Property<string>("ClusteringAlgorithm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DuplicateDetectionPrecision")
                        .HasColumnType("float");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackItemCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThemeCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProcessingRuns");
                });

            modelBuilder.Entity("ScheduledDigestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriticalActionItemsCount")
                        .HasColumnType("int");

                    b.Property<string>("DigestContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackCount")
                        .HasColumnType("int");

                    b.Property<int>("NewThemesCount")
                        .HasColumnType("int");

                    b.Property<string>("RecipientEmailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WeekEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("WeekStart");

                    b.ToTable("ScheduledDigestRuns");
                });

            modelBuilder.Entity("Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AffectedProductAreasJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedSegmentsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AverageSentimentScore")
                        .HasColumnType("float");

                    b.Property<double>("AverageUrgencyScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackCount")
                        .HasColumnType("int");

                    b.Property<double>("ImpactScore")
                        .HasColumnType("float");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ProcessingRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("RelevanceScore")
                        .HasColumnType("float");

                    b.Property<string>("ThemeHashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Label");

                    b.HasIndex("ProcessingRunId");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("ThemeCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageSimilarity")
                        .HasColumnType("float");

                    b.Property<string>("CentroidEmbeddingJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClusterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("SilhouetteScore")
                        .HasColumnType("float");

                    b.Property<Guid?>("SuggestedThemeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingRunId");

                    b.HasIndex("SuggestedThemeId");

                    b.ToTable("ThemeClusters");
                });

            modelBuilder.Entity("ThemeEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedAffectedCustomers")
                        .HasColumnType("int");

                    b.Property<Guid>("EvaluationRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("FeedbackPercentage")
                        .HasColumnType("float");

                    b.Property<bool>("MetRelevanceThreshold")
                        .HasColumnType("bit");

                    b.Property<double>("RelevanceScore")
                        .HasColumnType("float");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Trend")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationRunId");

                    b.HasIndex("ThemeId");

                    b.ToTable("ThemeEvaluations");
                });

            modelBuilder.Entity("ActionRecommendation", b =>
                {
                    b.HasOne("Theme", "Theme")
                        .WithMany("ActionRecommendations")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("ActionRecommendationEvaluation", b =>
                {
                    b.HasOne("ActionRecommendation", "ActionRecommendation")
                        .WithMany()
                        .HasForeignKey("ActionRecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluationRun", "EvaluationRun")
                        .WithMany("ActionRecommendationEvaluations")
                        .HasForeignKey("EvaluationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionRecommendation");

                    b.Navigation("EvaluationRun");
                });

            modelBuilder.Entity("EvaluationRun", b =>
                {
                    b.HasOne("ProcessingRun", "ProcessingRun")
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessingRun");
                });

            modelBuilder.Entity("FeedbackItem", b =>
                {
                    b.HasOne("ThemeCluster", "ThemeCluster")
                        .WithMany("FeedbackItems")
                        .HasForeignKey("ThemeClusterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Theme", "Theme")
                        .WithMany("FeedbackItems")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Theme");

                    b.Navigation("ThemeCluster");
                });

            modelBuilder.Entity("Theme", b =>
                {
                    b.HasOne("ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ThemeCluster", b =>
                {
                    b.HasOne("ProcessingRun", null)
                        .WithMany("Clusters")
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Theme", "SuggestedTheme")
                        .WithMany("Clusters")
                        .HasForeignKey("SuggestedThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SuggestedTheme");
                });

            modelBuilder.Entity("ThemeEvaluation", b =>
                {
                    b.HasOne("EvaluationRun", "EvaluationRun")
                        .WithMany("ThemeEvaluations")
                        .HasForeignKey("EvaluationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Theme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationRun");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("EvaluationRun", b =>
                {
                    b.Navigation("ActionRecommendationEvaluations");

                    b.Navigation("ThemeEvaluations");
                });

            modelBuilder.Entity("ProcessingRun", b =>
                {
                    b.Navigation("Clusters");
                });

            modelBuilder.Entity("Theme", b =>
                {
                    b.Navigation("ActionRecommendations");

                    b.Navigation("Clusters");

                    b.Navigation("FeedbackItems");
                });

            modelBuilder.Entity("ThemeCluster", b =>
                {
                    b.Navigation("FeedbackItems");
                });
#pragma warning restore 612, 618
        }
    }
}
